#!/bin/sh

# IPv4 link-local addresses (zeroconf) are
# only applicable on the 'inet' address family
[ "X$ADDRFAM" != "Xinet" ] && exit 0

# However there are some methods where it doesn't
# make any sense to configure an IPv4LL address

# not on loopback
[ "X$METHOD" = "Xloopback" ] && exit 0

# not on ppp or wvdial either
[ "X$METHOD" = "Xppp" ] && exit 0
[ "X$METHOD" = "Xwvdial" ] && exit 0

# The administrator may have blacklisted interfaces
# or only want zeroconf in a fallback situation
[ -f /etc/default/zeroconf ] &&
    . /etc/default/zeroconf

for BLACK in $IFBLACKLIST; do
    case $IFACE in
	$BLACK)
	exit 0
	;;
    esac
done

# should we only allocate an address if we do not already have one?
if [ -n "$FALLBACK" ]; then
    /bin/ip addr show $IFACE scope global | grep -q "inet"
    IP=$?
    [ $IP -eq 0 ] && exit 0
    if [ $IP -eq 0 ]; then
        /bin/ip route add 169.254.0.0/16 dev $IFACE
        exit 0
    fi
fi

# otherwise, we are good to go
/usr/local/sbin/zeroconf -i $IFACE

exit 0
